project: 
  type: website
  output-dir: "." 

website:
  title: "Jason Copella"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Project
        href: NBAProjectCopella.qmd
      - text: Proposal
        href: projectproposal.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: R Basics
        href: danl-399-quarto-r.qmd 
      - text: Dashboard
        href: danl-399-quarto-r.qmd 
          
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Jason Copella, 2024"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false


